sudo: require
services: -docker

before-install:
  - docker build -t imranirshad/react-docker-flow -f Dockerfile.dev .

script:
  - docker run imranirshad/react-docker-flow npm run test -- --coverage
