FROM node:alpine

# Create app directory
RUN mkdir -p /src/app
WORKDIR /src/app


# Install app dependencies
COPY package.json /src/app/
RUN npm install 

# Bundle app source

# COPY . /src/app
# because we referenced our app to local directory, we commented the copy option out. 

# Build and optimize react app
# RUN npm run build

EXPOSE 3000


CMD ["npm","run","start"]